/**
 * Commercial Control Plane Routes — Commander SDR
 *
 * Internal Seiertech application boundary.
 * Source: Spec #47 Commercial Control Plane Route Re-Confirmation
 */

import type { RouteEntry } from './types';

export const controlPlaneRoutes: RouteEntry[] = [
  {
    path: '/customers',
    label: 'Customers',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'customers',
    sortOrder: 1,
  },
  {
    path: '/tenants',
    label: 'Tenants',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'tenants',
    sortOrder: 2,
  },
  {
    path: '/instances',
    label: 'Instances',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'instances',
    sortOrder: 3,
  },
  {
    path: '/licences',
    label: 'Licences',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'licences',
    sortOrder: 4,
  },
  {
    path: '/entitlements',
    label: 'Entitlements',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '19-rbac-entitlement-feature-flags',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'entitlements',
    sortOrder: 5,
  },
  {
    path: '/modules',
    label: 'Modules',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'modules',
    sortOrder: 6,
  },
  {
    path: '/feature-flags',
    label: 'Feature Flags',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '19-rbac-entitlement-feature-flags',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'feature-flags',
    sortOrder: 7,
  },
  {
    path: '/deployment-rings',
    label: 'Deployment Rings',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'deployment',
    sortOrder: 8,
  },
  {
    path: '/trials-demo-dogfood',
    label: 'Trials / Demo / Dogfood',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'trials',
    sortOrder: 9,
  },
  {
    path: '/support-access',
    label: 'Support Access',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'support',
    sortOrder: 10,
  },
  {
    path: '/self-hosted-licence-files',
    label: 'Self-Hosted Licence Files',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'licence-files',
    sortOrder: 11,
  },
  {
    path: '/emergency-controls',
    label: 'Emergency Controls',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'emergency',
    sortOrder: 12,
  },
  {
    path: '/operator-audit',
    label: 'Operator Audit',
    boundary: 'control-plane',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['control-plane'],
    rbac: ['Seiertech Operator'],
    showInNav: true,
    icon: 'operator-audit',
    sortOrder: 13,
  },
];
