/**
 * Route Registry — Commander SDR
 *
 * This is the single source of truth for all application routes.
 * Routes are registry-driven per Spec #56 and Spec #47.
 * No route may be removed because a shell omits it.
 *
 * Source authority:
 * - docs/06_ui_build_reference/ROUTE_REGISTRY_BASELINE.md
 * - docs/06_ui_build_reference/source_47_Application_Route_and_Navigation_Register.md
 * - Spec #56 Shell Reference vs Build Authority Doctrine
 */

import type { RouteEntry } from './types';

export const operationalRoutes: RouteEntry[] = [
  // === v1.1 BUILD routes ===
  {
    path: '/',
    label: 'Command Centre',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '05-command-centre',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'command-centre',
    sortOrder: 1,
  },
  {
    path: '/cases',
    label: 'Case Queue',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '06-case-management',
    workspaces: ['drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'cases',
    sortOrder: 2,
  },
  {
    path: '/cases/:id',
    label: 'Case Detail',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '06-case-management',
    workspaces: ['drift-operations'],
    rbac: [],
    showInNav: false,
    sortOrder: 3,
  },
  {
    path: '/cases/analytics',
    label: 'Case Analytics',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '06-case-management',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: ['CISO', 'SOM', 'Security Analyst'],
    showInNav: false,
    parentPath: '/cases',
    sortOrder: 3.5,
  },
  {
    path: '/commander-ai',
    label: 'Commander AI',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '20-commander-ai-core',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'commander-ai',
    sortOrder: 4,
  },
  // === v1.2 SCAFFOLD routes ===
  {
    path: '/vulnerabilities',
    label: 'Vulnerability Management',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.2',
    owningSpec: '07-vulnerability-management',
    workspaces: ['drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'vulnerabilities',
    sortOrder: 10,
  },
  {
    path: '/exposure',
    label: 'Exposure Management',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.2',
    owningSpec: '08-exposure-management',
    workspaces: ['drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'exposure',
    sortOrder: 11,
  },
  {
    path: '/assets',
    label: 'Asset Intelligence',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.2',
    owningSpec: '19-asset-intelligence-surface',
    workspaces: ['identity-asset-intelligence'],
    rbac: [],
    showInNav: true,
    icon: 'assets',
    sortOrder: 12,
  },
  {
    path: '/identity',
    label: 'Identity Intelligence',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.2',
    owningSpec: '18-identity-intelligence-surface',
    workspaces: ['identity-asset-intelligence'],
    rbac: ['CISO', 'SOM', 'Security Analyst', 'Identity/Access Specialist', 'Security Architect', 'Risk Analyst', 'Risk/Adherence/Audit'],
    showInNav: true,
    icon: 'identity',
    sortOrder: 13,
  },
  {
    path: '/controls',
    label: 'Control Coverage',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.2',
    owningSpec: '11-control-coverage-editable-baselines',
    workspaces: ['control-architecture'],
    rbac: [],
    showInNav: true,
    icon: 'controls',
    sortOrder: 14,
  },
  {
    path: '/architecture',
    label: 'Architecture / Topology',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.2',
    owningSpec: '12-architecture-topology',
    workspaces: ['control-architecture'],
    rbac: [],
    showInNav: true,
    icon: 'architecture',
    sortOrder: 15,
  },
  {
    path: '/governance',
    label: 'Governance Reporting',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.2',
    owningSpec: '22-governance-reporting',
    workspaces: ['assurance-audit'],
    rbac: [],
    showInNav: true,
    icon: 'governance',
    sortOrder: 16,
  },
  {
    path: '/som/ciso',
    label: 'CISO Dashboard',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.5',
    owningSpec: 'som-management-views',
    workspaces: ['executive-posture'],
    rbac: ['CISO'],
    showInNav: true,
    icon: 'ciso',
    sortOrder: 50,
  },
  {
    path: '/som/security-operations',
    label: 'Security Operations Manager',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.5',
    owningSpec: 'som-management-views',
    workspaces: ['drift-operations'],
    rbac: ['SOM'],
    showInNav: true,
    icon: 'som',
    sortOrder: 51,
  },
  {
    path: '/som/architecture',
    label: 'Architecture Manager',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.5',
    owningSpec: 'som-management-views',
    workspaces: ['drift-operations'],
    rbac: ['Domain Lead'],
    showInNav: true,
    icon: 'som',
    sortOrder: 52,
  },
  {
    path: '/som/risk',
    label: 'Risk Manager',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.5',
    owningSpec: 'som-management-views',
    workspaces: ['drift-operations'],
    rbac: ['Domain Lead'],
    showInNav: true,
    icon: 'som',
    sortOrder: 53,
  },
  {
    path: '/som/cloud-security',
    label: 'Cloud Security Manager',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.5',
    owningSpec: 'som-management-views',
    workspaces: ['drift-operations'],
    rbac: ['Domain Lead'],
    showInNav: true,
    icon: 'som',
    sortOrder: 54,
  },
  // === v1.4 SCAFFOLD routes ===
  {
    path: '/security-c2',
    label: 'Security Command and Control',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '13-security-c2',
    workspaces: ['executive-posture'],
    rbac: [],
    showInNav: true,
    icon: 'security-c2',
    sortOrder: 20,
  },
  {
    path: '/ooda',
    label: 'OODA Views',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '14-ooda-views',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'ooda',
    sortOrder: 21,
  },
  {
    path: '/direction-boards',
    label: 'Direction Boards',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '15-direction-boards',
    workspaces: ['drift-operations', 'control-architecture'],
    rbac: [],
    showInNav: true,
    icon: 'direction-boards',
    sortOrder: 22,
  },
  {
    path: '/war-room/p0',
    label: 'P0 Zero-Day War Room',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '24-security-c2-p0-war-room',
    workspaces: ['drift-operations'],
    rbac: [],
    showInNav: true,
    icon: 'war-room',
    sortOrder: 23,
  },
  // === Operating Pictures (Units 20/21 — SCAFFOLD; drill-path targets for Unit 16a Command Centre) ===
  {
    path: '/operating-picture/external',
    label: 'External Operating Picture',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '20-external-operating-picture',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: [],
    showInNav: false,
    sortOrder: 24,
  },
  {
    path: '/operating-picture/internal',
    label: 'Internal Operating Picture',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.4',
    owningSpec: '21-internal-operating-picture',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: ['CISO', 'SOM', 'Security Analyst', 'Identity/Access Specialist', 'Security Architect', 'Risk Analyst', 'Risk/Adherence/Audit'],
    showInNav: false,
    sortOrder: 25,
  },
  // === v1.5 STUB routes ===
  {
    path: '/transformation',
    label: 'Transformation & M&A',
    boundary: 'operational',
    status: 'SCAFFOLD',
    version: 'v1.4',
    owningSpec: '01-application-shell-navigation-route-registry',
    workspaces: ['transformation-ma'],
    rbac: [],
    showInNav: true,
    icon: 'transformation',
    sortOrder: 25,
  },
  // === Strategy Centre (Spec #32 — build-blocking) ===
  {
    path: '/strategy',
    label: 'Strategy Centre',
    boundary: 'operational',
    status: 'BUILD',
    version: 'v1.1',
    owningSpec: '43-strategy-layer-runtime-surface',
    workspaces: ['executive-posture', 'drift-operations'],
    rbac: ['SOM', 'CISO', 'Tenant Admin'],
    showInNav: true,
    icon: 'strategy',
    sortOrder: 5,
  },
  {
    path: '/architecture/aws-ai-runtime-evaluation',
    label: 'AWS/Bedrock/AgentCore Evaluation',
    boundary: 'operational',
    status: 'STUB',
    version: 'v1.5',
    owningSpec: '21-aws-bedrock-agentcore-evaluation',
    workspaces: ['platform'],
    rbac: ['Platform Engineering'],
    showInNav: false,
    sortOrder: 30,
  },
];
