/**
 * Tenant Admin Routes — Commander C2
 *
 * Separate application boundary per three-application doctrine.
 * Source: Spec #47 v2.5.1 Tenant Admin Route Re-Confirmation
 */

import type { RouteEntry } from './types';

export const tenantAdminRoutes: RouteEntry[] = [
  {
    path: '/settings/tenant',
    label: 'Tenant Overview',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'tenant',
    sortOrder: 1,
  },
  {
    path: '/settings/users-rbac',
    label: 'Users & RBAC',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '19-rbac-entitlement-feature-flags',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'users',
    sortOrder: 2,
  },
  {
    path: '/settings/connectors',
    label: 'Connectors & Data Sources',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '16-connector-framework',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'connectors',
    sortOrder: 3,
  },
  {
    path: '/settings/features',
    label: 'Feature Availability',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '19-rbac-entitlement-feature-flags',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'features',
    sortOrder: 4,
  },
  {
    path: '/settings/sla',
    label: 'SLA Configuration',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'sla',
    sortOrder: 5,
  },
  {
    path: '/settings/routing',
    label: 'Routing Configuration',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'routing',
    sortOrder: 6,
  },
  {
    path: '/settings/validation',
    label: 'Validation Rules',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'validation',
    sortOrder: 7,
  },
  {
    path: '/settings/closure-reopening',
    label: 'Closure & Reopening',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'closure',
    sortOrder: 8,
  },
  {
    path: '/settings/p0-zero-day',
    label: 'P0 / Zero-Day Config',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'p0',
    sortOrder: 9,
  },
  {
    path: '/settings/automation-boundaries',
    label: 'Automation Boundaries',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'automation',
    sortOrder: 10,
  },
  {
    path: '/settings/commander-ai',
    label: 'Commander AI Config',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '20-commander-ai-core',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'commander-ai',
    sortOrder: 11,
  },
  {
    path: '/settings/audit-export',
    label: 'Audit & Export',
    boundary: 'tenant-admin',
    status: 'SCAFFOLD',
    version: 'v1.3',
    owningSpec: '18-tenant-admin',
    workspaces: ['admin'],
    rbac: ['Tenant Admin'],
    showInNav: true,
    icon: 'audit',
    sortOrder: 12,
  },
];
