// @ts-nocheck — Phase 4 migration: thesis snake_case rename in progress
/**
 * War Room Close-Out Model — Commander C2
 *
 * Source: WRCEP-1.0 War Room Communication Excellence Proposal (Phase 1)
 *
 * Pure function for generating immutable close-out reports.
 * Generated by: 'close-out-engine'
 *
 * Constraints:
 * - Close-out report is immutable once generated
 * - Lessons/recommendations are AI-generated but require review (requiresReview: true)
 * - All communication records are modelled as intent/status (Phase 1)
 */

import type { WarRoom, WarRoomMember, WarRoomSubscriber } from '../contracts/src/entities/war-room';

// ─── Input Shapes ────────────────────────────────────────────────────────────

export interface CloseOutCaseSummary {
  caseId: string;
  caseRef: string;
  status: string;
  priority: string;
  resolvedAt: string | null;
}

export interface AuditTimelineEntry {
  timestamp: string;
  actor: string;
  action: string;
  detail: string;
}

export interface MemberParticipation {
  userId: string;
  role: string;
  joinedAt: string;
  leftAt: string | null;
  actionsCount: number;
  decisionsCount: number;
}

export interface CommunicationRecord {
  channel: string;
  direction: 'outbound' | 'inbound';
  timestamp: string;
  summary: string;
}

export interface AiRecord {
  briefingVersion: number;
  generatedAt: string;
  recommendationsGenerated: number;
  recommendationsActioned: number;
  recommendationsDeclined: number;
}

export interface DecisionRecord {
  decisionId: string;
  description: string;
  decidedBy: string;
  decidedAt: string;
  outcome: string;
}

export interface EvidenceChainEntry {
  evidenceId: string;
  type: string;
  description: string;
  collectedAt: string;
  source: string;
}

// ─── Close-Out Report Value Object ───────────────────────────────────────────

export interface LessonRecommendation {
  description: string;
  category: string;
  requiresReview: true;
}

export interface CloseOutReport {
  warRoomRef: string;
  activationTimestamp: string;
  closureTimestamp: string;
  totalDuration: string;
  executiveSummary: string;
  boundCases: CloseOutCaseSummary[];
  timeline: AuditTimelineEntry[];
  membershipRecord: MemberParticipation[];
  subscriberRecord: WarRoomSubscriber[];
  aiAnalysisRecord: {
    briefingVersions: number;
    recommendationsGenerated: number;
    recommendationsActioned: number;
    recommendationsDeclined: number;
  };
  communicationRecord: {
    outbound: number;
    inbound: number;
    teams: number;
    adaptiveCards: number;
  };
  decisionsRecord: DecisionRecord[];
  evidenceChain: EvidenceChainEntry[];
  lessonsRecommendations: LessonRecommendation[];
  reportId: string;
  generatedAt: string;
  generatedBy: 'close-out-engine';
}

// ─── Close-Out Report Generation ─────────────────────────────────────────────

/**
 * Generate an immutable close-out report for a War Room.
 *
 * @param warRoom - The War Room being closed (must be in 'closed' status or transitioning)
 * @param cases - All bound cases with resolution status
 * @param auditTimeline - Complete audit timeline
 * @param memberParticipation - Member participation records
 * @param communicationRecords - All communication records
 * @param aiRecords - AI briefing history
 * @param decisions - Decisions made during the War Room
 * @param evidenceChain - Evidence collected
 */
export function generateCloseOutReport(
  warRoom: WarRoom,
  cases: CloseOutCaseSummary[],
  auditTimeline: AuditTimelineEntry[],
  memberParticipation: MemberParticipation[],
  communicationRecords: CommunicationRecord[],
  aiRecords: AiRecord[],
  decisions: DecisionRecord[],
  evidenceChain: EvidenceChainEntry[],
): CloseOutReport {
  const now = new Date().toISOString();
  const activationTime = new Date(warRoom.createdAt).getTime();
  const closureTime = Date.now();
  const durationMs = closureTime - activationTime;
  const durationHours = Math.floor(durationMs / (1000 * 60 * 60));
  const durationMinutes = Math.floor((durationMs % (1000 * 60 * 60)) / (1000 * 60));
  const totalDuration = `${durationHours}h ${durationMinutes}m`;

  // Aggregate AI analysis
  const totalBriefingVersions = aiRecords.length > 0
    ? Math.max(...aiRecords.map((r) => r.briefingVersion))
    : 0;
  const totalRecommendationsGenerated = aiRecords.reduce((sum, r) => sum + r.recommendationsGenerated, 0);
  const totalRecommendationsActioned = aiRecords.reduce((sum, r) => sum + r.recommendationsActioned, 0);
  const totalRecommendationsDeclined = aiRecords.reduce((sum, r) => sum + r.recommendationsDeclined, 0);

  // Aggregate communication
  const outbound = communicationRecords.filter((c) => c.direction === 'outbound').length;
  const inbound = communicationRecords.filter((c) => c.direction === 'inbound').length;
  const teams = communicationRecords.filter((c) => c.channel === 'teams').length;
  const adaptiveCards = communicationRecords.filter((c) => c.channel === 'teams_adaptive_card').length;

  // Executive summary
  const resolvedCount = cases.filter((c) => c.resolvedAt !== null).length;
  const executiveSummary = `War Room '${warRoom.warRoomRef}' operated for ${totalDuration}. ` +
    `${cases.length} case(s) bound, ${resolvedCount} resolved. ` +
    `${decisions.length} decision(s) recorded. ` +
    `${memberParticipation.length} member(s) participated. ` +
    `AI generated ${totalRecommendationsGenerated} recommendation(s), ` +
    `${totalRecommendationsActioned} actioned, ${totalRecommendationsDeclined} declined.`;

  // AI-generated lessons (require review)
  const lessonsRecommendations: LessonRecommendation[] = generateLessons(
    warRoom,
    cases,
    communicationRecords,
    aiRecords,
    decisions,
  );

  return {
    warRoomRef: warRoom.warRoomRef,
    activationTimestamp: warRoom.createdAt,
    closureTimestamp: now,
    totalDuration,
    executiveSummary,
    boundCases: cases,
    timeline: auditTimeline,
    membershipRecord: memberParticipation,
    subscriberRecord: [...warRoom.subscribers],
    aiAnalysisRecord: {
      briefingVersions: totalBriefingVersions,
      recommendationsGenerated: totalRecommendationsGenerated,
      recommendationsActioned: totalRecommendationsActioned,
      recommendationsDeclined: totalRecommendationsDeclined,
    },
    communicationRecord: {
      outbound,
      inbound,
      teams,
      adaptiveCards,
    },
    decisionsRecord: decisions,
    evidenceChain,
    lessonsRecommendations,
    reportId: `closeout-${warRoom.warRoomRef}-${Date.now()}`,
    generatedAt: now,
    generatedBy: 'close-out-engine',
  };
}

/**
 * Generate AI lessons/recommendations for post-incident review.
 * All lessons have requiresReview: true — they are recommendations, not facts.
 */
function generateLessons(
  warRoom: WarRoom,
  cases: CloseOutCaseSummary[],
  communicationRecords: CommunicationRecord[],
  aiRecords: AiRecord[],
  decisions: DecisionRecord[],
): LessonRecommendation[] {
  const lessons: LessonRecommendation[] = [];

  // Lesson: Response time
  if (cases.length > 0) {
    lessons.push({
      description: `War Room coordinated ${cases.length} case(s). Review whether binding was timely and complete.`,
      category: 'coordination',
      requiresReview: true,
    });
  }

  // Lesson: Communication effectiveness
  if (communicationRecords.length === 0) {
    lessons.push({
      description: 'No communication records captured. Consider whether stakeholder communication cadence was adequate.',
      category: 'communication',
      requiresReview: true,
    });
  }

  // Lesson: AI utilisation
  const totalGenerated = aiRecords.reduce((sum, r) => sum + r.recommendationsGenerated, 0);
  const totalActioned = aiRecords.reduce((sum, r) => sum + r.recommendationsActioned, 0);
  if (totalGenerated > 0 && totalActioned === 0) {
    lessons.push({
      description: 'AI recommendations were generated but none were actioned. Review whether recommendations were relevant or actionable.',
      category: 'ai-effectiveness',
      requiresReview: true,
    });
  }

  // Lesson: Decision velocity
  if (decisions.length > 0) {
    lessons.push({
      description: `${decisions.length} decision(s) recorded. Review decision latency and escalation effectiveness.`,
      category: 'decision-making',
      requiresReview: true,
    });
  }

  return lessons;
}
